from __future__ import annotations

# HFSS worker execution contract events
EXPORT_REPORTS_STARTED = "EXPORT_REPORTS_STARTED"
EXPORT_REPORTS_DONE = "EXPORT_REPORTS_DONE"
PACKAGE_ZIP_STARTED = "PACKAGE_ZIP_STARTED"
PACKAGE_ZIP_DONE = "PACKAGE_ZIP_DONE"
AEDT_DELETE_REMOTE_DONE = "AEDT_DELETE_REMOTE_DONE"
AEDT_DELETE_LOCAL_DONE = "AEDT_DELETE_LOCAL_DONE"
AEDT_DELETE_LOCAL_FAILED = "AEDT_DELETE_LOCAL_FAILED"
AEDT_RETENTION_VIOLATION_DETECTED = "AEDT_RETENTION_VIOLATION_DETECTED"

# Reconciliation / operations events
RECONCILE_PENDING_TTL_REQUEUE = "RECONCILE_PENDING_TTL_REQUEUE"
RECONCILE_PENDING_TTL_REQUEUE_CONFLICT = "RECONCILE_PENDING_TTL_REQUEUE_CONFLICT"
RECONCILE_PENDING_TTL_REQUEUE_FAILED = "RECONCILE_PENDING_TTL_REQUEUE_FAILED"
RECONCILE_PENDING_TO_UPLOADED = "RECONCILE_PENDING_TO_UPLOADED"
RECONCILE_UPLOADED_TO_PENDING = "RECONCILE_UPLOADED_TO_PENDING"
RECONCILE_RETRY_PENDING_FROM_FAILED_UPLOAD = "RECONCILE_RETRY_PENDING_FROM_FAILED_UPLOAD"
RECONCILE_UPLOAD_SOURCE_MISSING = "RECONCILE_UPLOAD_SOURCE_MISSING"
RECONCILE_DONE_ZIP_RECOVERED = "RECONCILE_DONE_ZIP_RECOVERED"
RECONCILE_DONE_ZIP_MISSING = "RECONCILE_DONE_ZIP_MISSING"
RECONCILE_ORPHAN_DONE_ZIP_REGISTERED = "RECONCILE_ORPHAN_DONE_ZIP_REGISTERED"

# Results collection events
COLLECT_STARTED = "COLLECT_STARTED"
COLLECT_DONE = "COLLECT_DONE"
COLLECT_DUPLICATE_SKIPPED = "COLLECT_DUPLICATE_SKIPPED"
COLLECT_FAILED = "COLLECT_FAILED"
